# Generated by Django 2.0.6 on 2018-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180611_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fpublicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
